version: '3'

networks:
  wordpress_network:
    driver: bridge

services:
# Nginx Proxy Manager
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt
    networks:
      - wordpress_network
  
# Wordpress and wp-cli
  wp:
    image: wordpress:latest
    ports:
      - ${IP}:${PORT}:80
    volumes:
      - ./wordpress/config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wordpress/wp-app/wp-config.php:/var/www/html/wp-config.php
      - ./wordpress/wp-app/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    networks:
      - wordpress_network

  wpcli:
    image: wordpress:cli
    volumes:
      - ./wordpress/config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wordpress/wp-app/wp-config.php:/var/www/html/wp-config.php
      - ./wordpress/wp-app/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
      - wp
    networks:
      - wordpress_network

# PhpMyAdmin and MySQL
  pma:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      UPLOAD_LIMIT: 50M
    ports:
      - ${IP}:8080:80
    volumes:
     - ./database/config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
     - ./database/config/pma_config.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - db
    networks:
      - wordpress_network

  db:
    image: mariadb:lts
    ports:
      - ${IP}:3306:3306
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./database/wp-data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    networks:
      - wordpress_network
